[package]
name = "compromise"
version = "0.1.0"
authors = ["videah <videah@selfish.systems>"]
license = "MIT"
repository = "https://github.com/videah/compromise"

[dependencies]
clap = {version = "2.27.1", features = ["yaml"]}
image = "*"
